# 각 yaml의 변수 파일
db:
  repository: antiwater19/lab2-mydb
  tag: v1
  replicas: 1

redis:
  repository: antiwater19/lab2-myredis
  tag: v1
  replicas: 1

app:
  repository: public.ecr.aws/r9n4c1b3/minsu/testingapp
  tag: can-run-github-actions-ssh-auth-with-github-secret
  replicas: 2

nginx:
  repository: antiwater19/lab2-mynginx
  tag: v1
  replicas: 1


ingress:
  healthCheckPath: /healthz
  host: app.jumpi.store
  certificateArn: arn:aws:acm:ap-northeast-2:504301552141:certificate/97ed9a57-8445-44e0-9d88-ac81b4087493
  group:
    name: shared-alb
    order: "10"
